Generalize mock call
Post the `AsyncMock` changes in 3.8.0, the default `mode` was no longer
set to `"r"`:
```
$ python --version
Python 3.8.0rc1+
$ python -m unittest mock_open.test
.....F..............................
======================================================================
FAIL: test_default_mode (mock_open.test.test_mocks.TestModes)
Default mode is 'r'.
----------------------------------------------------------------------
Traceback (most recent call last):
  ...
AssertionError: expected call not found.
Expected: open('/path/to/file', 'r')
Actual: open('/path/to/file')
----------------------------------------------------------------------
Ran 36 tests in 0.185s
FAILED (failures=1)
```

This is because `CallableMock.__call__` doesn't call `_mock_call`
directly any longer, but to `_mock_check_sig`, `_increment_mock_call`
and then `_mock_call`. `_increment_mock_call` is used to increment the
call count in async mocks, while `_mock_call` calls `_execute_mock_call`
to do the actual mocking stuff like side-effects and return values.

So because we didn't set the default value high enough in the call
chain, `_increment_mock_call` never saw the default mode value.

Instead of overriding `_mock_open`, we now override `__call__` directly.
This should fix this and hopefully future changes as well.